package com.example.axtro.core.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF407BFF)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF2C6CF0)
val onPrimaryContainerLight = Color(0xFFFEFCFF)
val secondaryLight = Color(0xFF495D93)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFAEC2FF)
val onSecondaryContainerLight = Color(0xFF3B4F84)
val tertiaryLight = Color(0xFF902EA8)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFAC4AC3)
val onTertiaryContainerLight = Color(0xFFFFFBFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFf2F6FC)
val onBackgroundLight = Color(0xFF191B23)
val surfaceLight = Color(0xFFFAF8FF)
val onSurfaceLight = Color(0xFF191B23)
val surfaceVariantLight = Color(0xFFDFE2F3)
val onSurfaceVariantLight = Color(0xFF424654)
val outlineLight = Color(0xFF737686)
val outlineVariantLight = Color(0xFFC3C6D7)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E3039)
val inverseOnSurfaceLight = Color(0xFFF0F0FB)
val inversePrimaryLight = Color(0xFFB2C5FF)
val surfaceDimLight = Color(0xFFD9D9E4)
val surfaceBrightLight = Color(0xFFFAF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF2F3FE)
val surfaceContainerLight = Color(0xFFEDEDF8)
val surfaceContainerHighLight = Color(0xFFE7E7F3)
val surfaceContainerHighestLight = Color(0xFFE1E2ED)

val primaryDark = Color(0xFFB2C5FF)
val onPrimaryDark = Color(0xFF002B74)
val primaryContainerDark = Color(0xFF5D8BFF)
val onPrimaryContainerDark = Color(0xFF001746)
val secondaryDark = Color(0xFFB2C5FF)
val onSecondaryDark = Color(0xFF182E61)
val secondaryContainerDark = Color(0xFF33477C)
val onSecondaryContainerDark = Color(0xFFA3B7F3)
val tertiaryDark = Color(0xFFF4AEFF)
val onTertiaryDark = Color(0xFF55006A)
val tertiaryContainerDark = Color(0xFFCC68E2)
val onTertiaryContainerDark = Color(0xFF330040)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF11131B)
val onBackgroundDark = Color(0xFFE1E2ED)
val surfaceDark = Color(0xFF11131B)
val onSurfaceDark = Color(0xFFE1E2ED)
val surfaceVariantDark = Color(0xFF424654)
val onSurfaceVariantDark = Color(0xFFC3C6D7)
val outlineDark = Color(0xFF8D90A0)
val outlineVariantDark = Color(0xFF424654)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE1E2ED)
val inverseOnSurfaceDark = Color(0xFF2E3039)
val inversePrimaryDark = Color(0xFF0055D4)
val surfaceDimDark = Color(0xFF11131B)
val surfaceBrightDark = Color(0xFF373941)
val surfaceContainerLowestDark = Color(0xFF0C0E15)
val surfaceContainerLowDark = Color(0xFF191B23)
val surfaceContainerDark = Color(0xFF1D1F27)
val surfaceContainerHighDark = Color(0xFF272A32)
val surfaceContainerHighestDark = Color(0xFF32343D)







